name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Set up Fyne
      run: |
        sudo apt-get install -y gcc libgl1-mesa-dev xorg-dev libxkbcommon-dev
        go get fyne.io/fyne/v2@latest
        go install fyne.io/tools/cmd/fyne@latest

    - name: Setup Android SDK Tools
      uses: android-actions/setup-android@v3.2.1  

    - name: Test Everything is installed
      run: |
        go version        
        fyne version
        sdkmanager --version

    - name: Build 
      run: | 
        # cd ${{ github.workspace }}/cmd/saatool
        # go build
        # cd ${{ github.workspace }}/cmd/satooltool
        # go build
        SOURCE_DIR=${{ github.workspace }}/cmd/saatool
        APP_ICON=$SOURCE_DIR/icon.png
        fyne package --target android/arm64 --app-id org.saatool.app --source-dir $SOURCE_DIR --name "SAATOOL" --icon $APP_ICON


        